name: Daily Build

on:
  # repository_dispatch:
  #   types:
  #     - build
  push:

env:
  BUILD_NUMBER: ${{ github.event.client_payload.number }}
  YEAR: ${{ github.event.client_payload.year }}
  MONTH: ${{ github.event.client_payload.month }}
  DAY: ${{ github.event.client_payload.day }}
  WORKSPACE: ${{ github.workspace }}


jobs:
  source-code:
    name: Check out and process source code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1 --rebase
      - name: Set daily build
        shell: bash
        run: ./tools/GHAction/process_sources.sh
      - name: Upload Source bundle
        uses: actions/upload-artifact@v1
        with:
          name: corona_src
          path: ./corona_src.tgz

  iOS-template:
    needs: source-code
    runs-on: macos-latest
    steps:
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: corona_src
      - name: Unpack source code
        shell: bash
        run: tar -xzf ./corona_src.tgz
      - name: Build iOS templates
        shell: bash
        working-directory: ./platform/iphone
        run: ./gh_build_templates.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload iOS templates
        uses: actions/upload-artifact@v1
        with:
          name: iOS-Templates
          path: ./ios_output.zip
  tvOS-template:
    needs: source-code
    runs-on: macos-latest
    steps:
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: corona_src
      - name: Unpack source code
        shell: bash
        run: tar -xzf ./corona_src.tgz
      - name: Build tvOS templates
        shell: bash
        working-directory: ./platform/tvos
        run: ./gh_build_templates.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload tvOS templates
        uses: actions/upload-artifact@v1
        with:
          name: tvOS-Templates
          path: ./tvos_output.zip
  native:
    needs: source-code
    runs-on: macos-latest
    steps:
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: corona_src
      - name: Unpack source code
        shell: bash
        run: tar -xzf ./corona_src.tgz
      - name: Build Corona Native
        shell: bash
        run: ./tools/GHAction/build_native.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload Corona Native
        uses: actions/upload-artifact@v1
        with:
          name: native
          path: ./CoronaNative.tar.gz

  macOS-Simulator:
    needs:
      - source-code
      - tvOS-template
      - iOS-template
    runs-on: macos-latest
    steps:
      - run: echo "All done"
