name: Daily Build

on:
  # repository_dispatch:
  #   types:
  #     - build
  push:

env:
  BUILD_NUMBER: ${{ github.event.client_payload.number }}
  YEAR: ${{ github.event.client_payload.year }}
  MONTH: ${{ github.event.client_payload.month }}
  DAY: ${{ github.event.client_payload.day }}
  WORKSPACE: ${{ github.workspace }}


jobs:
  source-code:
    name: Check out and process source code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1 --rebase
      - name: Set daily build
        run: ./tools/GHAction/process_sources.sh
      - name: Upload Source bundle
        uses: actions/upload-artifact@v1
        with:
          name: SourceCode
          path: ./output

  iOS-template:
    needs: source-code
    runs-on: macos-latest
    steps:
      # - uses: actions/cache@v1
      #   id: cache
      #   with:
      #     path: ./output
      #     key: ios-2021-corona
      - name: Get processed code
        # if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        # if: steps.cache.outputs.cache-hit != 'true'
        run: tar -xzf SourceCode/corona.tgz
      - name: Build iOS templates
        # if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./platform/iphone
        run: ./gh_build_templates.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload iOS templates
        uses: actions/upload-artifact@v1
        with:
          name: iOS-Templates
          path: ./output
  tvOS-template:
    needs: source-code
    runs-on: macos-latest
    steps:
      # - uses: actions/cache@v1
      #   id: cache
      #   with:
      #     path: ./output
      #     key: tvos-2021-corona
      - name: Get processed code
        # if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        # if: steps.cache.outputs.cache-hit != 'true'
        run: tar -xzf SourceCode/corona.tgz
      - name: Build tvOS templates
        # if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./platform/tvos
        run: ./gh_build_templates.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload tvOS templates
        uses: actions/upload-artifact@v1
        with:
          name: tvOS-Templates
          path: ./output
  native:
    needs: source-code
    runs-on: macos-latest
    steps:
      # - uses: actions/cache@v1
      #   id: cache
      #   with:
      #     path: ./output
      #     key: native-2021-corona
      - name: Get processed code
        # if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        # if: steps.cache.outputs.cache-hit != 'true'
        run: tar -xzf SourceCode/corona.tgz
      - name: Build Corona Native
        # if: steps.cache.outputs.cache-hit != 'true'
        run: ./tools/GHAction/build_native.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload Corona Native
        uses: actions/upload-artifact@v1
        with:
          name: Native
          path: ./output

  macOS-Simulator:
    needs:
      - source-code
      - tvOS-template
      - iOS-template
      - native
    runs-on: macos-latest
    steps:
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        run: tar -xzf SourceCode/corona.tgz
      - name: Get iOS templates
        uses: actions/download-artifact@v1
        with:
          name: iOS-templates
      - name: Put iOS templates in place
        run: cp -v iOS-templates/* platform/resources/iostemplate/
      - name: Get tvOS templates
        uses: actions/download-artifact@v1
        with:
          name: tvOS-templates
      - name: Put iOS templates in place
        run: cp -v tvOS-templates/* platform/resources/iostemplate/
      # todo
      # platform/resources/webtemplate.zip
      # platform/resources/linuxtemplate.tar.gz
      # platform/resources/raspbiantemplate.tar.gz
      - run: mkdir docs
      - name: Get Sample Code
        uses: actions/checkout@v2
        with:
          repository: coronalabs/samples-coronasdk
          path: docs/SampleCode
      - name: Clean-up docs
        run: rm -rf docs/SampleCode/.git docs/SampleCode/.gitignore
      - name: Get Corona Native
        uses: actions/download-artifact@v1
        with:
          name: Native
      - name: install appdmg
        run: npm install -g appdmg
      - name: install imagemagick
        run: brew install imagemagick gs
      - name: Build DMG
        run: ./tools/GHAction/build_dmg.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload macOS Daily build artifact
        uses: actions/upload-artifact@v1
        with:
          name: Corona DMG
          path: ./output
